conky.config = {
    alignment = 'top_right',
    gap_x = 20,
    gap_y = 40,

    minimum_width = 350,
    maximum_width = 350,
    minimum_height = 380,

    background = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'override',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 230,
    own_window_colour = '0d0d0d',
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',

    double_buffer = true,
    no_buffers = true,
    update_interval = 2,
    cpu_avg_samples = 2,

    use_xft = true,
    font = 'Hack:size=11',

    default_color = 'ffffff',
    color0 = 'ffffff',
    color1 = '888888',
}

conky.text = [[
${alignc}${font Hack:bold:size=26}${time %H:%M}${font}
${alignc}${color1}${time %a, %b %d}${color0}


cpu${alignr}${cpu}%
${cpubar 10,348}


memory${alignr}${exec free -h | awk '/^Mem:/ {print tolower($3) "/" tolower($2)}' | sed 's/gi/g/g'}
${membar 10,348}


disk${alignr}${exec df -h / | awk 'NR==2 {print tolower($3) "/" tolower($2)}' | sed 's/gi/g/g'}
${fs_bar 10,348 /}


swap${alignr}${exec free -h | awk '/^Swap:/ {print tolower($3) "/" tolower($2)}' | sed 's/gi/g/g'}
${swapbar 10,348}

kernel${alignr}${kernel}
uptime${alignr}${uptime_short}
]]
